version: '3.1'

services:
    memcache:
        image: memcached
        restart: "no"
        ports:
            - 11211:11211
    mongo:
        image: mongo
        restart: "no"
        ports:
            - 27017:27017
